---
# Use the new container infrastructure
sudo: false
dist: trusty
language: python
python: '2.7'

addons:
  apt:
    packages: python-pip

# Install ansible
install: pip install ansible

# Basic role syntax check
script: cd tests && ansible-playbook -i inventory test.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
